; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = 
	ttn_sandbox_lorawan_sx1262-v11-a-01

[radiolib]
lib_deps = https://github.com/PCo-IoT-2024/RadioLib.git

[gps]
build_flags = 
	-D GPS_SERIAL_PORT=2
	-D GPS_SERIAL_BAUD_RATE=9600
	-D GPS_SERIAL_CONFIG=SERIAL_8N1
	-D GPS_SERIAL_RX_PIN=16
	-D GPS_SERIAL_TX_PIN=17
lib_deps = mikalhart/TinyGPSPlus

[eu868]
build_flags = 
	-D RADIOLIB_LORA_REGION=EU868
	-D RADIOLIB_LORA_SUBBANDS=0

[voc_radiolib_tmp_v110_1_1]
build_flags = 
	-D RADIOLIB_LORAWAN_DEV_EUI="0x70B3D57ED006AF2B"
	-D RADIOLIB_LORAWAN_APP_KEY="0x26, 0xFD, 0x49, 0x41, 0x8E, 0xC9, 0xAC, 0xE9, 0x7A, 0xD8, 0xCE, 0x14, 0x83, 0xED, 0xD4, 0x00"
	-D RADIOLIB_LORAWAN_NWK_KEY="0x65, 0xB5, 0x3D, 0xCD, 0xEC, 0xE6, 0xAC, 0x36, 0x73, 0xE8, 0x2B, 0x6A, 0xD6, 0xDA, 0x7D, 0x93"

[voc_radiolib_tmp_1]
build_flags = 
	-D RADIOLIB_LORAWAN_DEV_EUI="0x70B3D57ED006AF06"
	-D RADIOLIB_LORAWAN_APP_KEY="0x9D, 0xAB, 0xD0, 0xC7, 0xE0, 0x82, 0xF2, 0x9A, 0xCD, 0xC7, 0x13, 0x8F, 0x17, 0xF8, 0x47, 0x64"

[sx1262-v11-a-01]
build_flags = 
	-D RADIOLIB_LORAWAN_DEV_EUI="0x70B3D57ED00771C2"
	-D RADIOLIB_LORAWAN_APP_KEY="0xCF, 0x46, 0x84, 0xF4, 0x76, 0xAC, 0x01, 0x51, 0x53, 0xA3, 0x2B, 0xF3, 0x3B, 0x65, 0x5E, 0x3B"
	-D RADIOLIB_LORAWAN_NWK_KEY="0xF0, 0x32, 0xC4, 0x16, 0xDA, 0xCA, 0x43, 0x1C, 0x8C, 0xCD, 0xF1, 0x17, 0x21, 0x53, 0x5D, 0x67"

[voc-experiment-1-110]
build_flags = 
	-D RADIOLIB_LORAWAN_DEV_EUI="0x70B3D57ED006B069"
	-D RADIOLIB_LORAWAN_APP_KEY="0x50, 0x94, 0x11, 0xA7, 0x1E, 0x13, 0x16, 0xE3, 0x4F, 0xDD, 0xFF, 0x0E, 0xA6, 0x06, 0x29, 0x85"
	-D RADIOLIB_LORAWAN_NWK_KEY="0x0C, 0xA5, 0x90, 0x8F, 0x18, 0x89, 0xA4, 0xE3, 0x99, 0xA3, 0xC2, 0x0A, 0xFF, 0x9F, 0x77, 0x45"

[0001-plant-00-00]
build_flags = 
	-D RADIOLIB_LORAWAN_DEV_EUI="0x70B3D57ED006B307"
	-D RADIOLIB_LORAWAN_APP_KEY="0x14, 0x70, 0xFC, 0x7A, 0xD8, 0x20, 0x9E, 0xFF, 0x48, 0xA9, 0xC7, 0xCD, 0xD6, 0x12, 0x4C, 0xF8"
	-D RADIOLIB_LORAWAN_NWK_KEY="0x95, 0xBF, 0x84, 0x5A, 0xAA, 0x41, 0x6C, 0x96, 0xC8, 0x3B, 0xA8, 0x3C, 0x94, 0x81, 0x7C, 0x36"

[message_104]
build_flags = 
	-D RADIOLIB_LORAWAN_PAYLOAD="\"RadioLib v1.0.4 device: Waiting for GPS\""

[message_110]
build_flags = 
	-D RADIOLIB_LORAWAN_PAYLOAD="\"RadioLib v1.1.0 device: Waiting for GPS\""

[message_experiment_110]
build_flags = 
	-D RADIOLIB_LORAWAN_PAYLOAD="\"RadioLib v1.1.0 experiment device: Waiting for GPS\""

[sx1276]
build_flags = 
	-D RADIOLIB_LORA_MODULE=SX1276
	-D RADIOLIB_EXCLUDE_CC1101
	-D RADIOLIB_EXCLUDE_SX126X
	-D RADIOLIB_EXCLUDE_LR11X0
	-D RADIOLIB_EXCLUDE_RF69
	-D RADIOLIB_EXCLUDE_RFM2X
	-D RADIOLIB_EXCLUDE_SX1231
	-D RADIOLIB_EXCLUDE_SX128X
	-D RADIOLIB_EXCLUDE_SI443X
	-D RADIOLIB_EXCLUDE_NRF24

[sx1262]
build_flags = 
	-D RADIOLIB_LORA_MODULE=SX1262
	-D RADIOLIB_EXCLUDE_CC1101
	-D RADIOLIB_EXCLUDE_LR11X0
	-D RADIOLIB_EXCLUDE_RF69
	-D RADIOLIB_EXCLUDE_RFM2X
	-D RADIOLIB_EXCLUDE_SX1231
	-D RADIOLIB_EXCLUDE_SX127X
	-D RADIOLIB_EXCLUDE_SX128X
	-D RADIOLIB_EXCLUDE_SI443X
	-D RADIOLIB_EXCLUDE_NRF24

[sx1276_radiolib_esp32dev]
lib_deps = 
	${radiolib.lib_deps}
build_flags = 
	${sx1276.build_flags}
	-D RADIOLIB_LORA_MODULE_BITMAP="5, 2, 14, 4"

[sx1276_radiolib_wemos_d1_mini32]
lib_deps = 
	${radiolib.lib_deps}
build_flags = 
	${sx1276.build_flags}
	-D RADIOLIB_LORA_MODULE_BITMAP="5, 2, 14, 4"

[sx1262_radiolib_esp32dev]
lib_deps = 
	${radiolib.lib_deps}
build_flags = 
	${sx1262.build_flags}
	-D RADIOLIB_LORA_MODULE_BITMAP="5, 2, 14, 4"

[ttn_sandbox]
build_flags = 
	-D RADIOLIB_LORAWAN_JOIN_EUI="0x0000000000000000"

[ttn_sandbox_lorawan]
build_flags = 
	${ttn_sandbox.build_flags}
	-D RADIOLIB_EXCLUDE_AFSK
	-D RADIOLIB_EXCLUDE_APRS
	-D RADIOLIB_EXCLUDE_AX25
	-D RADIOLIB_EXCLUDE_BELL
	-D RADIOLIB_EXCLUDE_FSK4
	-D RADIOLIB_EXCLUDE_HELLSCHREIBER
	-D RADIOLIB_EXCLUDE_MORSE
	-D RADIOLIB_EXCLUDE_PAGER
	-D RADIOLIB_EXCLUDE_RTTY
	-D RADIOLIB_EXCLUDE_SSTV

[ttn_sandbox_lorawan_sx1276_radiolib_esp32]
lib_deps = 
	${sx1276_radiolib_esp32dev.lib_deps}
build_flags = 
	${ttn_sandbox_lorawan.build_flags}
	${sx1276_radiolib_esp32dev.build_flags}

[ttn_sandbox_lorawan_sx1276_radiolib_wemos_d1_mini32]
lib_deps = 
	${sx1276_radiolib_wemos_d1_mini32.lib_deps}
build_flags = 
	${ttn_sandbox_lorawan.build_flags}
	${sx1276_radiolib_wemos_d1_mini32.build_flags}

[ttn_sandbox_lorawan_sx1262_radiolib_esp32]
lib_deps = 
	${sx1262_radiolib_esp32dev.lib_deps}
build_flags = 
	${ttn_sandbox_lorawan.build_flags}
	${sx1262_radiolib_esp32dev.build_flags}

[env]
upload_port = COM3
monitor_speed = 115200

[env:ttn_sandbox_lorawan_v110_sx1276_radiolib_esp32dev_voc_radiolib_tmp_v110_1]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${ttn_sandbox_lorawan_sx1276_radiolib_esp32.lib_deps}
	${gps.lib_deps}
	adafruit/Adafruit BMP183 Unified Library@^1.1.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
build_flags = 
	${eu868.build_flags}
	${ttn_sandbox_lorawan_sx1276_radiolib_esp32.build_flags}
	${voc_radiolib_tmp_v110_1_1.build_flags}
	${message_110.build_flags}
	${gps.build_flags}
	-D RADIOLIB_LORA_UPLINK_INTERVAL_SECONDS="(1UL * 60UL)"

[env:ttn_sandbox_lorawan_sx1262-v11-a-01]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${ttn_sandbox_lorawan_sx1262_radiolib_esp32.lib_deps}
	${gps.lib_deps}
	adafruit/Adafruit BMP183 Unified Library@^1.1.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
build_flags = 
	${eu868.build_flags}
	${ttn_sandbox_lorawan_sx1262_radiolib_esp32.build_flags}
	${sx1262-v11-a-01.build_flags}
	${message_experiment_110.build_flags}
	${gps.build_flags}
	-D RADIOLIB_LORA_UPLINK_INTERVAL_SECONDS="(1UL * 60UL)"

[env:ttn_sandbox_lorawan_v104_sx1276_radiolib_esp32dev_voc_radiolib_tmp_1]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${ttn_sandbox_lorawan_sx1276_radiolib_esp32.lib_deps}
	${gps.lib_deps}
	adafruit/Adafruit BMP183 Unified Library@^1.1.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
build_flags = 
	${eu868.build_flags}
	${ttn_sandbox_lorawan_sx1276_radiolib_esp32.build_flags}
	${voc_radiolib_tmp_1.build_flags}
	${message_104.build_flags}
	${gps.build_flags}
	-D RADIOLIB_LORA_UPLINK_INTERVAL_SECONDS="(1UL * 60UL)"

[env:ttn_sandbox_lorawan_v110_sx1276_radiolib_esp32dev_voc_experiment_1_110]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${ttn_sandbox_lorawan_sx1276_radiolib_esp32.lib_deps}
	${gps.lib_deps}
	adafruit/Adafruit BMP183 Unified Library@^1.1.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
build_flags = 
	${eu868.build_flags}
	${ttn_sandbox_lorawan_sx1276_radiolib_esp32.build_flags}
	${voc-experiment-1-110.build_flags}
	${message_experiment_110.build_flags}
	${gps.build_flags}
	-D RADIOLIB_LORA_UPLINK_INTERVAL_SECONDS="(1UL * 60UL)"

[env:ttn_sandbox_lorawan_v110_sx1276_radiolib_esp32dev_plantpal]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	${ttn_sandbox_lorawan_sx1276_radiolib_esp32.lib_deps}
	${gps.lib_deps}
	adafruit/Adafruit BMP183 Unified Library@^1.1.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
build_flags = 
	${eu868.build_flags}
	${ttn_sandbox_lorawan_sx1276_radiolib_esp32.build_flags}
	${0001-plant-00-00.build_flags}
	${message_experiment_110.build_flags}
	${gps.build_flags}
	-D RADIOLIB_LORA_UPLINK_INTERVAL_SECONDS="(1UL * 60UL)"

[env:ttn_sandbox_lorawan_v110_sx1276_radiolib_wemos_d1_mini32_voc_radiolib_tmp_v110_1]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = 
	${ttn_sandbox_lorawan_sx1276_radiolib_wemos_d1_mini32.lib_deps}
	${gps.lib_deps}
	adafruit/Adafruit BMP183 Unified Library@^1.1.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
build_flags = 
	${eu868.build_flags}
	${ttn_sandbox_lorawan_sx1276_radiolib_wemos_d1_mini32.build_flags}
	${voc_radiolib_tmp_v110_1_1.build_flags}
	${message_110.build_flags}
	${gps.build_flags}
	-D RADIOLIB_LORA_UPLINK_INTERVAL_SECONDS="(1UL * 60UL)"

[env:ttn_sandbox_lorawan_v104_sx1276_radiolib_wemos_d1_mini32_voc_radiolib_tmp_1]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
lib_deps = 
	${ttn_sandbox_lorawan_sx1276_radiolib_wemos_d1_mini32.lib_deps}
	${gps.lib_deps}
	adafruit/Adafruit BMP183 Unified Library@^1.1.3
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
build_flags = 
	${eu868.build_flags}
	${ttn_sandbox_lorawan_sx1276_radiolib_wemos_d1_mini32.build_flags}
	${voc_radiolib_tmp_1.build_flags}
	${message_104.build_flags}
	${gps.build_flags}
	-D RADIOLIB_LORA_UPLINK_INTERVAL_SECONDS="(1UL * 60UL)"